M48
; DRILL file {KiCad 8.0.4} date 2024-09-20T16:59:51-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-20T16:59:51-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.7402Y-3.1496
X3.7402Y-5.8268
X5.7874Y-3.1496
X5.7874Y-5.8268
M30
